### ISSUE TITLE
关于配置问题

### ISSUE THREAD

**Issue by zhong0215** [asd920/Auto-jd#10]
在secrets已经配置好了以下内容，云函数页面是否还需要进行其他配置
![image](https://user-images.githubusercontent.com/86042665/122375260-a3326e00-cf95-11eb-98a4-0512266469ea.png)
![image](https://user-images.githubusercontent.com/86042665/122375354-bb09f200-cf95-11eb-85f2-9abee930bbe5.png)

**Comment by asd920** [comment]
PHSH_KEY 最好也写上

**Comment by zhong0215** [comment]
> PHSH_KEY 最好也写上

写上了，但是我发现运行有一部分活动会出现用户未登录，是我的cookie问题吗
![image](https://user-images.githubusercontent.com/86042665/122382383-73d32f80-cf9c-11eb-91a0-da0c1d22bf7d.png)

**Comment by asd920** [comment]
> > PHSH_KEY 最好也写上
> 
> 写上了，但是我发现运行有一部分活动会出现用户未登录，是我的cookie问题吗
> ![image](https://user-images.githubusercontent.com/86042665/122382383-73d32f80-cf9c-11eb-91a0-da0c1d22bf7d.png)
> 

pt_key=xxxxxxx;pt_pin=xxx;    cookie要这个格式

**Comment by zhong0215** [comment]
> > > PHSH_KEY 最好也写上
> > 
> > 
> > 写了，但我发现运行有个别活动会出现用户未登录，是我的饼干问题吗？
> > ![图像](https://user-images.githubusercontent.com/86042665/122382383-73d32f80-cf9c-11eb-91a0-da0c1d22bf7d.png)
> 
> pt_key=xxxxxxx；pt_pin=xxx；cookie要这个格式

好的，谢谢

**Comment by lqc1314** [comment]
大佬,我部署成功后,点击测试的时候,日志打印出来是这样的
START RequestId:e0dee5da-ed2d-410c-ad23-1d0865e13e7b

2021-06-18T03:10:54.756Z  e0dee5da-ed2d-410c-ad23-1d0865e13e7b  TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

Response RequestId:e0dee5da-ed2d-410c-ad23-1d0865e13e7b RetMsg:null

END RequestId:e0dee5da-ed2d-410c-ad23-1d0865e13e7b

Report RequestId:e0dee5da-ed2d-410c-ad23-1d0865e13e7b Duration:1ms Memory:128MB MemUsage:9.792969MB

是不是哪里不对

**Comment by asd920** [comment]
你那个腾讯云函数运行环境选了什么

**Comment by lqc1314** [comment]
> 你那个腾讯云函数运行环境选了什么

node的环境,我已经配置好了大佬,谢谢了,是定时函数需要添加要运行的那些js名称,我添加了就可以了

**Comment by lqc1314** [comment]
> 你那个腾讯云函数运行环境选了什么

我把那些js名一个一个复制用&链接上去就可以了

**Comment by shaokaikai** [comment]
> > 你那个腾讯云函数运行环境选了什么
> 
> node的环境,我已经配置好了大佬,谢谢了,是定时函数需要添加要运行的那些js名称,我添加了就可以了

可以说的详细点吗

**Comment by lqc206** [comment]
大佬,为什么我部署按照教程走action里面没有 部署到云函数那个工作流啊,没办法部署,是需要进行什么操作么

**Comment by asd920** [comment]
> 
> 
> 大佬,为什么我部署按照教程走action里面没有 部署到云函数那个工作流啊,没办法部署,是需要进行什么操作么

deploy_tencent_scf.yml  找到这个文件，修改下就有了。

**Comment by lqc206** [comment]
> > 大佬,为什么我部署按照教程走action里面没有 部署到云函数那个工作流啊,没办法部署,是需要进行什么操作么
> 
> deploy_tencent_scf.yml 找到这个文件，修改下就有了。
大佬要怎么修改啊,小白搞不懂啊...

**Comment by lqc206** [comment]
> > 大佬,为什么我部署按照教程走action里面没有 部署到云函数那个工作流啊,没办法部署,是需要进行什么操作么
> 
> deploy_tencent_scf.yml 找到这个文件，修改下就有了。

出来了大佬,谢谢大佬了,再麻烦问下,直接部署上就可以了么,是自动就会执行么,还需要进行什么操作让他执行么
