### ISSUE TITLE
关注有礼怎么运行 错误

### ISSUE THREAD

**Issue by shaokaikai** [asd920/Auto-jd#12]

**Comment by shaokaikai** [comment]
2021-06-21T01:06:24.430Z  a5d95869-564d-4dd6-acdf-48f5a09c7adf  TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

**Comment by shaokaikai** [comment]
求大佬帮帮

**Comment by asd920** [comment]
> 求大佬帮帮

脚本名是哪个?

**Comment by shaokaikai** [comment]
jd_monk_inter_shop_sign.js

**Comment by shaokaikai** [comment]
> > 求大佬帮帮
> 
> 脚本名是哪个?

有办法解决吗
