### ISSUE TITLE
dalao新活动 燃动夏季什么时候可以添加一下

### ISSUE THREAD

**Issue by jjlyt2** [asd920/Auto-jd#25]

**Comment by asd920** [comment]
> 
> 
> _No description provided._

已添加

**Comment by 86xqs** [comment]
> > _没有提供说明。_
> 
> 已添加

燃动夏季运行不了，就是一堆错误代码。

**Comment by 86xqs** [comment]
> > _没有提供说明。_
> 
> 已添加

🔔燃动夏季, 开始!
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './MovementFaker.js'
Require stack:
- /ql/scripts/asd920_Auto-jd_jd_summer_movement.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd_jd_summer_movement.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_summer_movement.js' ]
}

**Comment by asd920** [comment]
你没更新获取我最新脚本，我试过云函数和v2p都是没问题的

**Comment by 86xqs** [comment]
> 你没更新获取我最新脚本，我试过云函数和v2p都是没问题的

那我就不懂了，你最近更新至少是在一小时前，而我是刚刚才更新的。

**Comment by jjlyt2** [comment]
感谢dalao, 我测试执行是正常跑的没错误
