### ISSUE TITLE
燃动夏季报错，缺少MovementFaker.init

### ISSUE THREAD

**Issue by ymcoming** [asd920/Auto-jd#32]
❗️燃动夏季, 错误!
TypeError: Cannot read property 'init' of undefined
    at MovementFaker.init (/ql/scripts/asd920_Auto-jd_asd920_Auto-jd_jd_summer_movement.js:885:7163)
    at async MovementFaker.run (/ql/scripts/asd920_Auto-jd_asd920_Auto-jd_jd_summer_movement.js:885:5353)
    at async getBody (/ql/scripts/asd920_Auto-jd_asd920_Auto-jd_jd_summer_movement.js:885:9403)
    at async /ql/scripts/asd920_Auto-jd_asd920_Auto-jd_jd_summer_movement.js:720:19
{"code":"1","echo":"required string parameter 'functionId' is not present"}

**Comment by baicuhaha** [comment]
+1  本地node服务 跑起来错误一样。。。

**Comment by asd920** [comment]
现在燃动都跑不了了，过几小时又火爆了
