### ISSUE TITLE
宠汪汪

### ISSUE THREAD

**Issue by cnhap** [asd920/Auto-jd#51]
大神 宠汪汪 如何修复呀  有没有教程 安装的 青龙v2.9.3  用之前的方法 设置了 不起效

**Comment by asd920** [comment]
> 大神 宠汪汪 如何修复呀 有没有教程 安装的 青龙v2.9.3 用之前的方法 设置了 不起效

你要设置啥

**Comment by cnhap** [comment]
## 开始执行... 2021-09-22 10:15:57



🔔宠汪汪, 开始!
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './JDJRValidator_Aaron'
Require stack:
- /ql/scripts/asd920_Auto-jd_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd_jd_joy.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
}

## 执行结束... 2021-09-22 10:15:57 耗时 0 秒


脚本 跑不起来

**Comment by BlueHtml** [comment]
@asd920 宠汪汪 运行报错：`Cannot find module './JDJRValidator_Aaron'`。
看了下库里确实是不存在`JDJRValidator_Aaron`的，只有一个`JDJRValidator_Pure`。
另外发现是[这次提交](https://github.com/BlueHtml/Auto-jd/commit/b50490820c07c86d8217ea9ecea2e0e9c71aad98#diff-d02db6f1379ad0df1a65d2a115e3470436d330ab9a15ff3ee1cab3c5d6e99aeeL29)把`JDJRValidator_Pure`改成了`JDJRValidator_Aaron`。
是与上游没同步完成？还是更新有误？能否修正一下？

**Comment by cnhap** [comment]
==================脚本执行- 北京时间(UTC+8)：2021/9/23 下午9:10:21=====================


***********开始【京东账号1】xxxxxx********

收取鹅蛋失败:入参错误
兑换金币失败:入参错误

***********开始【京东账号2】xxxxxx********

收取鹅蛋失败:入参错误
兑换金币失败:入参错误

***********开始【京东账号3】xxxxxx********

收取鹅蛋失败:入参错误
兑换金币失败:入参错误

----------------------------------------------------------------

我的天天提鹅  也是报上面的错误

**Comment by cnhap** [comment]
❗️京喜工厂, 错误!
ReferenceError: helpAuthor is not defined
    at jdDreamFactory (/ql/scripts/asd920_Auto-jd_jd_dreamFactory.js:152:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /ql/scripts/asd920_Auto-jd_jd_dreamFactory.js:95:7


现在助力码 好像也不正常  几天了 都没有 内部助力  已经添加  code.sh  和定时任务  
<html>
<body>


task code.sh
--



</body>
</html>
<html>
<body>


task code.sh
--



</body>
</html>
<html>
<body>


task code.sh
--



</body>
</html>
<html>
<body>


task code.sh
--



</body>
</html>

**Comment by BlueHtml** [comment]
@cnhap 我简单修复了下，你可以参考一下：https://github.com/BlueHtml/Auto-jd
@asd920 已提PR

**Comment by BlueHtml** [comment]
@asd920 还是报错，暂时切换回了老版本

**Comment by cnhap** [comment]
> 已修复，感谢提醒

## 开始执行... 2021-09-29 15:03:14



🔔宠汪汪, 开始!
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './JDJRValidator__Pure'
Require stack:
- /ql/scripts/asd920_Auto-jd_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd_jd_joy.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
}

## 执行结束... 2021-09-29 15:03:14 耗时 0 秒

我删除 脚本 重新 拉取的脚本 还是不行呀

**Comment by asd920** [comment]
> > 已修复，感谢提醒
> 
> ## 开始执行... 2021-09-29 15:03:14
> 🔔宠汪汪, 开始! internal/modules/cjs/loader.js:892 throw err; ^
> 
> Error: Cannot find module './JDJRValidator__Pure' Require stack:
> 
> * /ql/scripts/asd920_Auto-jd_jd_joy.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/ql/scripts/asd920_Auto-jd_jd_joy.js:28:18)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
>   }
> 
> ## 执行结束... 2021-09-29 15:03:14 耗时 0 秒
> 我删除 脚本 重新 拉取的脚本 还是不行呀
修复了

**Comment by cnhap** [comment]
> > 修复了

大佬 内部互助的 有没有修复呀 现在都不会内部互助.
