### ISSUE TITLE
日志-京东饭粒   错误

### ISSUE THREAD

**Issue by wangyuan0217** [asd920/Auto-jd#66]
❗️京东饭粒, 错误!
TypeError: Cannot read property 'msg' of null
    at /ql/scripts/asd920_Auto-jd_jd_fanli.js:224:57
    at got.post.then.message (/ql/scripts/asd920_Auto-jd_jd_fanli.js:344:5772)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

❗️京东饭粒, 错误!
ReferenceError: uid is not defined
    at /ql/scripts/asd920_Auto-jd_jd_fanli.js:168:68
    at new Promise (<anonymous>)
    at saveTaskRecord (/ql/scripts/asd920_Auto-jd_jd_fanli.js:167:12)
    at /ql/scripts/asd920_Auto-jd_jd_fanli.js:149:43

**Comment by wangyuan0217** [comment]
❗️领券中心签到, 错误!
TypeError: Cannot read property 'couponConfig' of undefined
    at /ql/scripts/asd920_Auto-jd_jd_ccSign.js:98:29
    at got.post.then.message (/ql/scripts/asd920_Auto-jd_jd_ccSign.js:323:5772)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by wangyuan0217** [comment]
❌ 口袋书店, 失败! 原因: TypeError: Cannot read property 'storeGold' of undefined!

**Comment by wangyuan0217** [comment]
❗️京东排行榜, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /ql/scripts/asd920_Auto-jd_jd_rankingList.js:78:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/asd920_Auto-jd_jd_rankingList.js:239:4791)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

❗️京东排行榜, 错误!
TypeError: Cannot read property 'signTask' of undefined
    at /ql/scripts/asd920_Auto-jd_jd_rankingList.js:110:37
    at got.post.then.message (/ql/scripts/asd920_Auto-jd_jd_rankingList.js:239:5694)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by wangyuan0217** [comment]
❗️删除优惠券, 错误!
SyntaxError: Unexpected token ) in JSON at position 25
    at JSON.parse (<anonymous>)
    at /ql/scripts/asd920_Auto-jd_jd_delCoupon.js:77:21
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/asd920_Auto-jd_jd_delCoupon.js:238:4774)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by asd920** [comment]
谢谢提醒
