### ISSUE TITLE
青龙 多合一签到报错

### ISSUE THREAD

**Issue by Talk1scheap** [asd920/Auto-jd#70]
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js
- /ql/scripts/asd920_Auto-jd/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js',
    '/ql/scripts/asd920_Auto-jd/JD_DailyBonus.js'
  ]
}
京东签到脚本执行异常:Error: Command failed: /usr/local/bin/node ./JD_DailyBonus.js >> ./result.txt
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js
- /ql/scripts/asd920_Auto-jd/JD_DailyBonus.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/asd920_Auto-jd/JDJRValidator_Pure.js',
    '/ql/scripts/asd920_Auto-jd/JD_DailyBonus.js'
  ]
}
```

**Comment by assassinors** [comment]
去机器对应目录执行下npm install png-js
