### ISSUE TITLE
手动同步最新代码后，部署到腾讯云，好多脚本直接报错

### ISSUE THREAD

**Issue by yumengbdw** [asd920/Auto-jd#75]
```
START RequestId:43a5e5d5-fbf9-4009-9a77-8e9506f91ea6
2022-01-10T03:03:00.335Z	43a5e5d5-fbf9-4009-9a77-8e9506f91ea6	jd_cfd
2022-01-10T03:03:00.473Z	43a5e5d5-fbf9-4009-9a77-8e9506f91ea6	/var/user/jd_cfd.js:1129
          $.showPp = data?.AreaAddr?.dwIsSHowPp ?? 0
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Runtime.exports.main_handler [as handler] (/var/user/index.js:32:11)
    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)
    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)
Response RequestId:43a5e5d5-fbf9-4009-9a77-8e9506f91ea6 RetMsg:null
END RequestId:43a5e5d5-fbf9-4009-9a77-8e9506f91ea6
Report RequestId:43a5e5d5-fbf9-4009-9a77-8e9506f91ea6 Duration:151ms Memory:128MB MemUsage:13.507812MB





START RequestId: fe834ba1-33e9-4c6d-87d1-6b519851f443

Init Report RequestId: fe834ba1-33e9-4c6d-87d1-6b519851f443 Coldstart: 617ms (PullCode: 364ms InitRuntime: 42ms InitFunction: 211ms) Memory: 128MB MemUsage: 7.36MB

2022-01-10T03:01:00.783Z fe834ba1-33e9-4c6d-87d1-6b519851f443 jd_daily_egg

2022-01-10T03:01:00.916Z fe834ba1-33e9-4c6d-87d1-6b519851f443 /var/user/jd_daily_egg.js:66

      $.token = (await downloadUrl("https://gia.jd.com/m.html")).match(/var\s*?jd_risk_token_id\s*?=\s*["`'](\S*?)["`'];?/)?.[1] || ""
```

    
```                                                                                                                        ^
SyntaxError: Unexpected token '.'

    at wrapSafe (internal/modules/cjs/loader.js:1072:16)

    at Module._compile (internal/modules/cjs/loader.js:1122:27)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

    at Module.load (internal/modules/cjs/loader.js:1002:32)

    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

    at Module.require (internal/modules/cjs/loader.js:1044:19)

    at require (internal/modules/cjs/helpers.js:77:18)

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:32:11)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

Response RequestId:fe834ba1-33e9-4c6d-87d1-6b519851f443 RetMsg:null

END RequestId:fe834ba1-33e9-4c6d-87d1-6b519851f443

Report RequestId:fe834ba1-33e9-4c6d-87d1-6b519851f443 Duration:139ms Memory:128MB MemUsage:15.867188MB
```

**Comment by asd920** [comment]
我更新了下yml，推荐使用docke青龙来运行脚本。

**Comment by BlueHtml** [comment]
@yumengbdw 腾讯云的yml有很多失效的，新的也没添加进去。
并且部署的node版本是12，脚本里的很多新语法是不支持的，运行就会报错。
也就是腾讯云版本几乎不维护了，使用其他的方式吧
