### ISSUE TITLE
jd_travel运行报错

### ISSUE THREAD

**Issue by yuflyfly** [asd920/Auto-jd#76]
START RequestId: a631de38-3650-42d4-b43d-8eced2b56627

Init Report RequestId: a631de38-3650-42d4-b43d-8eced2b56627 Coldstart: 407ms (PullCode: 340ms InitRuntime: 5ms InitFunction: 62ms) Memory: 128MB MemUsage: 7.39MB

2022-01-11T09:12:01.759Z a631de38-3650-42d4-b43d-8eced2b56627 jd_travel

2022-01-11T09:12:01.920Z a631de38-3650-42d4-b43d-8eced2b56627 /var/user/jd_travel.js:8

let wxCookieArr = process.env.WXCookie?.split("@") || []

                                       ^

SyntaxError: Unexpected token '.'

    at wrapSafe (internal/modules/cjs/loader.js:1072:16)

    at Module._compile (internal/modules/cjs/loader.js:1122:27)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

    at Module.load (internal/modules/cjs/loader.js:1002:32)

    at Function.Module._load (internal/modules/cjs/loader.js:901:14)

    at Module.require (internal/modules/cjs/loader.js:1044:19)

    at require (internal/modules/cjs/helpers.js:77:18)

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:32:11)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

Response RequestId:a631de38-3650-42d4-b43d-8eced2b56627 RetMsg:null

END RequestId:a631de38-3650-42d4-b43d-8eced2b56627

Report RequestId:a631de38-3650-42d4-b43d-8eced2b56627 Duration:165ms Memory:128MB MemUsage:16.543396MB

在腾讯云函数上面部署的，还有就是jd_travel的yml可以同步更新一下吗，感谢

**Comment by asd920** [comment]
> START RequestId: a631de38-3650-42d4-b43d-8eced2b56627
> 
> Init Report RequestId: a631de38-3650-42d4-b43d-8eced2b56627 Coldstart: 407ms (PullCode: 340ms InitRuntime: 5ms InitFunction: 62ms) Memory: 128MB MemUsage: 7.39MB
> 
> 2022-01-11T09:12:01.759Z a631de38-3650-42d4-b43d-8eced2b56627 jd_travel
> 
> 2022-01-11T09:12:01.920Z a631de38-3650-42d4-b43d-8eced2b56627 /var/user/jd_travel.js:8
> 
> let wxCookieArr = process.env.WXCookie?.split("@") || []
> 
> ```
>                                    ^
> ```
> 
> SyntaxError: Unexpected token '.'
> 
> ```
> at wrapSafe (internal/modules/cjs/loader.js:1072:16)
> 
> at Module._compile (internal/modules/cjs/loader.js:1122:27)
> 
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
> 
> at Module.load (internal/modules/cjs/loader.js:1002:32)
> 
> at Function.Module._load (internal/modules/cjs/loader.js:901:14)
> 
> at Module.require (internal/modules/cjs/loader.js:1044:19)
> 
> at require (internal/modules/cjs/helpers.js:77:18)
> 
> at Runtime.exports.main_handler [as handler] (/var/user/index.js:32:11)
> 
> at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)
> 
> at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)
> ```
> 
> Response RequestId:a631de38-3650-42d4-b43d-8eced2b56627 RetMsg:null
> 
> END RequestId:a631de38-3650-42d4-b43d-8eced2b56627
> 
> Report RequestId:a631de38-3650-42d4-b43d-8eced2b56627 Duration:165ms Memory:128MB MemUsage:16.543396MB
> 
> 在腾讯云函数上面部署的，还有就是jd_travel的yml可以同步更新一下吗，感谢

云函数用不了。
