### ISSUE TITLE
种豆得豆不能自动执行

### ISSUE THREAD

**Issue by tenlent** [asd920/Auto-jd#80]
种豆得豆不能自动执行

**Comment by asd920** [comment]
> 种豆得豆不能自动执行

发报错代码看看。

**Comment by Adangs** [comment]
> > 种豆得豆不能自动执行
> 
> 发报错代码看看。

单独执行jd_plantBean是可以的；但这个脚本好像不会自动执行？

**Comment by Adangs** [comment]
使用测试脚本 jd_speed&jd_bean_change
会报错误


- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)

    at Function.resolve (internal/modules/cjs/helpers.js:83:19)

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:31:40)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/var/user/index.js',

    '/var/runtime/node12/UserFunction.js',

    '/var/runtime/node12/Runtime.engine.js',

    '/var/runtime/node12/bootstrap.js'

  ]

}

Response RequestId:4145be76-5ca4-4eb6-8d7e-7ebd7861ec1e RetMsg:null

END RequestId:4145be76-5ca4-4eb6-8d7e-7ebd7861ec1e

Report RequestId:4145be76-5ca4-4eb6-8d7e-7ebd7861ec1e Duration:166ms Memory:128MB MemUsage:17.253906MB

**Comment by Adangs** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/5443355/155998942-6a48c68e-b8ea-472b-8584-49270c03d6d8.png">

**Comment by BlueHtml** [comment]
> <img alt="image" width="1116" src="https://user-images.githubusercontent.com/5443355/155998942-6a48c68e-b8ea-472b-8584-49270c03d6d8.png">

个人猜测：
`?.`语法需要Node14.0.0+才能支持。腾讯云脚本默认是node12，所以执行会报错。
你可以参照[这里](https://github.com/BlueHtml/Auto-jd/commit/63e2830f79d6ee5caf96ae40f059f886c727f6da)手动修改部署的node版本。我试过，成功了，这里是不报错了，不过其他还有一大堆错误。。
目前腾讯云方式处于无人维护状态，还是换其他方式吧，青龙或本地。
